version: "3"

services:
  app_container:
    build: ../server_5
    container_name: server_6
    
  nginx_container:
    image: nginx:latest
    container_name: nginx_6
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    
